import logo from './logo.svg';
import './App.css';
import Header from './components/Header/Header';
import Slider from './components/Slider/Slider';
import Footer from './components/Footer/Footer';

function App() {
  return (
    <div className="App">
      <Header></Header>
      <Slider></Slider>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet doloremque eius asperiores in animi veniam sapiente eos, ipsum quam quo deleniti alias ipsam necessitatibus harum at consectetur, consequuntur ea! Repellendus aliquid minus repellat molestias at odio error, praesentium minima illum. Dolorum pariatur corporis odit et necessitatibus magnam repudiandae deleniti saepe illo! Animi beatae, minima itaque maxime sunt necessitatibus eligendi blanditiis, modi laudantium perspiciatis delectus id provident aliquid omnis consequatur illum aspernatur. Consequuntur ullam veniam deleniti rerum nisi repudiandae, iste animi neque quia perferendis quisquam quibusdam natus voluptates aliquid dolore vel facere hic rem cum fugiat, beatae consequatur nam! Distinctio, voluptate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat quod laborum reiciendis illo, eaque delectus perferendis adipisci atque amet temporibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore magnam nulla molestiae ducimus, quia sapiente dignissimos velit repudiandae quis, dicta nihil asperiores. Consectetur vitae quibusdam eius porro ullam maxime, voluptate deleniti architecto rerum alias. Perferendis similique voluptates nisi enim molestiae doloribus corrupti recusandae mollitia veritatis? Rem et architecto rerum! Laborum consectetur qui nesciunt odit earum aspernatur dolorum mollitia illo, fuga perspiciatis repellendus veritatis. In repellendus sit est vitae? Soluta, architecto? Sequi, praesentium? Reiciendis ab aut, voluptatum, odio veritatis incidunt fugiat illum, quidem consectetur atque nisi? Veritatis provident quis repudiandae necessitatibus facere, quibusdam facilis amet a consequatur voluptatum dicta cumque reiciendis.
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet doloremque eius asperiores in animi veniam sapiente eos, ipsum quam quo deleniti alias ipsam necessitatibus harum at consectetur, consequuntur ea! Repellendus aliquid minus repellat molestias at odio error, praesentium minima illum. Dolorum pariatur corporis odit et necessitatibus magnam repudiandae deleniti saepe illo! Animi beatae, minima itaque maxime sunt necessitatibus eligendi blanditiis, modi laudantium perspiciatis delectus id provident aliquid omnis consequatur illum aspernatur. Consequuntur ullam veniam deleniti rerum nisi repudiandae, iste animi neque quia perferendis quisquam quibusdam natus voluptates aliquid dolore vel facere hic rem cum fugiat, beatae consequatur nam! Distinctio, voluptate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat quod laborum reiciendis illo, eaque delectus perferendis adipisci atque amet temporibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore magnam nulla molestiae ducimus, quia sapiente dignissimos velit repudiandae quis, dicta nihil asperiores. Consectetur vitae quibusdam eius porro ullam maxime, voluptate deleniti architecto rerum alias. Perferendis similique voluptates nisi enim molestiae doloribus corrupti recusandae mollitia veritatis? Rem et architecto rerum! Laborum consectetur qui nesciunt odit earum aspernatur dolorum mollitia illo, fuga perspiciatis repellendus veritatis. In repellendus sit est vitae? Soluta, architecto? Sequi, praesentium? Reiciendis ab aut, voluptatum, odio veritatis incidunt fugiat illum, quidem consectetur atque nisi? Veritatis provident quis repudiandae necessitatibus facere, quibusdam facilis amet a consequatur voluptatum dicta cumque reiciendis.
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet doloremque eius asperiores in animi veniam sapiente eos, ipsum quam quo deleniti alias ipsam necessitatibus harum at consectetur, consequuntur ea! Repellendus aliquid minus repellat molestias at odio error, praesentium minima illum. Dolorum pariatur corporis odit et necessitatibus magnam repudiandae deleniti saepe illo! Animi beatae, minima itaque maxime sunt necessitatibus eligendi blanditiis, modi laudantium perspiciatis delectus id provident aliquid omnis consequatur illum aspernatur. Consequuntur ullam veniam deleniti rerum nisi repudiandae, iste animi neque quia perferendis quisquam quibusdam natus voluptates aliquid dolore vel facere hic rem cum fugiat, beatae consequatur nam! Distinctio, voluptate. Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat quod laborum reiciendis illo, eaque delectus perferendis adipisci atque amet temporibus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore magnam nulla molestiae ducimus, quia sapiente dignissimos velit repudiandae quis, dicta nihil asperiores. Consectetur vitae quibusdam eius porro ullam maxime, voluptate deleniti architecto rerum alias. Perferendis similique voluptates nisi enim molestiae doloribus corrupti recusandae mollitia veritatis? Rem et architecto rerum! Laborum consectetur qui nesciunt odit earum aspernatur dolorum mollitia illo, fuga perspiciatis repellendus veritatis. In repellendus sit est vitae? Soluta, architecto? Sequi, praesentium? Reiciendis ab aut, voluptatum, odio veritatis incidunt fugiat illum, quidem consectetur atque nisi? Veritatis provident quis repudiandae necessitatibus facere, quibusdam facilis amet a consequatur voluptatum dicta cumque reiciendis.
      </p>
      <Footer></Footer>
    </div>
  );
}

export default App;
